//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UCCPrint.rc
//
#define IDC_APPLY                       3
#define IDD_SV_SA_TEMPLATE_DLG          62
#define IDD_MB_EVENT_EDITDLG7           63
#define IDI_ICON_BARCODE                64
#define IDB_MB_COMP_TYPE                65
#define IDD_BARCODE_DLG                 66
#define IDD_USER_PROP_DLG               67
#define IDB_BITMAP_DVD_590_463_BACK_IN  68
#define IDB_BITMAP_400_200_IN_LABEL     69
#define IDB_BITMAP_8700_5080_MM         70
#define IDB_BITMAP_350_200              71
#define IDR_FONT_BAR                    72
#define IDR_TOOLBAR_DRAW                73
#define IDD_DIALOG_CHART                74
#define IDD_SV_TEMLATE_DLG              96
#define IDD_ABOUTBOX                    100
#define IDD_CONTROLSAMPLE_DIALOG        102
#define IDD_APP_VIEW                    107
#define IDR_MAINFRAME                   128
#define IDR_UCCPRITYPE                  129
#define IDR_TOOLBAR_TEMP                130
#define IDB_TITLE                       131
#define IDD_DIALOG_LIST                 132
#define IDR_NEW_MENU                    133
#define IDB_BITMAP_262_100_IN_LABEL     134
#define IDB_BITMAP_LABEL_100_34_MM      135
#define IDB_BITMAP_CD_118_118_MM        136
#define IDB_MB_BITMAP_REMOVE            150
#define IDB_MB_BITMAP_MOVE_UP           151
#define IDB_MB_BITMAP_MOVE_DOWN         152
#define IDB_LOGO                        159
#define IDB_BITMAP_NEW                  170
#define IDB_BITMAP_OPEN                 171
#define IDB_BITMAP_OTHER                172
#define IDI_FILE_ICON                   173
#define IDR_SV_RICHEDIT_BAR             176
#define IDD_APP_LOOK                    180
#define IDD_MB_EVENT_EDITDLG6           185
#define IDD_DIALOG_DB_NAME              186
#define IDD_DIALOG_NEW_EVENT            187
#define IDD_MB_EVENT_PAGEDLG            188
#define IDB_MB_IMAGES_SMALL             189
#define IDB_MB_BITMAP_MAX               193
#define IDB_MB_BITMAP_MIN               194
#define IDB_MB_BITMAP_LIE               195
#define IDB_MB_IMAGES_NORMAL            196
#define IDD_MB_TEMPLATE_DIALOG          197
#define IDD_MB_NEW_TEMPLATE_PAGE0       199
#define IDD_HMI_SUBMENU_DLG             216
#define IDD_HMI_MENU_MAIN               220
#define IDD_SV_RICHEDIT_DLG             265
#define IDD_SV_SHAPE_TEXT_DLG           306
#define IDC_TAB                         1000
#define IDC_BUTTON1                     1001
#define IDC_HOMEPAGE                    1002
#define IDC_EDIT1                       1003
#define IDR_NEW_FORMAT                  1004
#define IDC_LIST1                       1005
#define IDC_SQLLIST                     1006
#define IDR_DRAWCOMPBAR_NEW1            1007
#define IDB_SPLASH                      1008
#define IDB_BITMAP_PIC                  1009
#define IDB_IMAGELIST                   1010
#define IDC_EDIT_EVENT_PARAM            1011
#define IDC_BUTTON_SELECT               1012
#define IDC_APP_LOOK2                   1013
#define IDC_CHECK1                      1014
#define IDC_CHECK2                      1015
#define IDC_EDIT_INDEX                  1016
#define IDC_ADD_PROJECT                 1017
#define IDC_TABPOS                      1018
#define IDC_BUTTON_NEW                  1019
#define IDC_BUTTON_OPEN                 1020
#define IDC_REMOVE_PROJECT              1021
#define IDC_SV_BARCODE_MODULE           1022
#define IDC_WORKSPACELIST               1023
#define IDC_EDIT_DBNAME                 1024
#define IDC_SV_BARCODE_SHOWTEXT         1025
#define IDC_SV_BARCODE_CHECKSUM         1026
#define IDC_SV_BARCODE_HORZ             1027
#define IDC_COMBO_EVENT                 1028
#define IDC_SV_BARCODE_CENTER           1029
#define IDC_APP_LOOK1                   1030
#define IDC_SHOW_AT_STARTUP             1031
#define IDC_XD_TP_DLG_TABPOS            1032
#define IDC_SV_BARCODE_SYMBOLOGY        1033
#define IDC_BUTTON_TEMPLATE             1034
#define IDC_SV_BARCODE_PADDING          1035
#define IDC_MOVE_DOWN                   1036
#define IDC_EDIT_CHOICELIST             1037
#define IDD_DIALOG_START                1038
#define IDD_CONNECTDLG                  1039
#define IDC_BUTTON_IMPORT               1040
#define IDC_BROWSEBUTTON                1041
#define IDC_DSNCOMBO                    1042
#define IDC_RADIOSNAPSHOT               1043
#define IDC_RADIODYNASET                1044
#define IDC_SQLEDIT                     1045
#define IDD_DIALOG_SETTING              1046
#define IDC_SV_SHAPE_TEXT               1047
#define IDC_SV_INSERT_USERINFO          1048
#define IDC_BUTTON_REMOVEALL            1049
#define IDR_TOOLBAR_TEMP1               1050
#define IDB_BITMAP1                     1051
#define IDB_BITMAP2                     1052
#define IDB_BITMAP3                     1053
#define IDB_BITMAP4                     1054
#define IDD_DIALOG_PAGE_OFFSET          1055
#define IDD_SUB_CONNECT                 1056
#define IDC_MOVE_UP                     1057
#define IDC_COMBO_DB                    1058
#define IDC_LST_DATA                    1059
#define IDC_SV_BARCODE_DEFAULT          1068
#define IDC_SV_BARCODE_MODULE_TYPE      1071
#define IDC_MB_PAGE_LIST                1090
#define IDC_MB_LIE_BUTTON               1095
#define IDC_MB_PREVIEW                  1096
#define IDC_MB_MIN_BUTTON               1097
#define IDC_MB_MSG                      1098
#define IDC_MB_LIST                     1100
#define IDC_MB_MAX_BUTTON               1101
#define IDC_SV_BARCODE_ORIENTATION      1188
#define IDC_SV_BARCODE_WIDENARROWRATIO  1189
#define IDC_SV_BARCODE_RIGHT            1194
#define IDC_SV_BARCODE_VERT             1196
#define IDC_SV_BARCODE_BOTTOM           1198
#define IDC_SV_BARCODE_ALIGN            1200
#define IDC_SV_BARCODE_CENTER2          1202
#define IDC_SV_BARCODE_RIGHT2           1204
#define IDC_MSG                         1230
#define IDC_SV_RICHEDIT_CONTROL         1241
#define IDC_BUTTON_REMOVE               1250
#define IDC_COMBO_COLUMN                1252
#define IDC_STATIC_DE1                  1355
#define IDC_STATIC_DE2                  1356
#define IDC_COMBO_FIELDS                1357
#define IDC_CHECK_LOAD                  1359
#define IDC_BUTTON_LOAD                 1360
#define IDC_EDIT_IMAGE                  1361
#define IDC_COMBO_DBNAME                1362
#define IDC_CHECK_PRINT_BORDER          1363
#define IDC_COMBO_CONNECT_TYPE          1366
#define IDC_EDIT_WIDTH                  1368
#define IDC_EDIT_HEIGHT                 1369
#define IDC_UNIT0                       1370
#define IDC_UNIT1                       1371
#define IDC_BUTTON_DB                   1372
#define IDC_COMBO_DB_MAIN               1373
#define IDC_BUTTON_EXECUTE              1374
#define IDC_RADIO_GRID_SOLID            1375
#define IDC_RADIO_GRID_DOT              1376
#define IDC_BUTTON_COLOR                1377
#define IDC_BUTTON_GRID_COLOR           1378
#define IDC_CHECK_HORZ                  1379
#define IDC_CHECK_VERT                  1380
#define IDC_EDIT_START                  1381
#define IDC_EDIT_TOTAL                  1382
#define IDC_LIST_CHART                  1383
#define IDC_SV_INSERT_TAB               1501
#define IDC_SV_INSERT_RETURN            1502
#define IDB_MB_BITMAP_NEW_CHART         22903
#define ID_VIEW_RULER                   32771
#define ID_DRAW_RECT                    32772
#define ID_DROPARROW                    32773
#define ID_DRAW_EDIT                    32774
#define ID_DRAW_GROUPBOX                32775
#define ID_VIEW_DRAWBAR                 32776
#define ID_VIEW_FORMATBAR               32777
#define ID_DRAW_RADIO                   32778
#define ID_FONT_STYLE_BOLD              32779
#define ID_FONT_STYLE_ITALIC            32780
#define ID_FONT_STYLE_UNDERLINE         32781
#define ID_FONT_LEFT_ALIGN              32782
#define ID_FONT_CENTER                  32783
#define ID_DRAW_SPINEDIT                32784
#define ID_DRAW_PROGRESS                32785
#define ID_FONT_BIG                     32786
#define ID_FONT_SMALL                   32787
#define ID_DRAW_SLIDER                  32788
#define ID_DRAW_SEPARATER               32789
#define ID_DRAW_ROUNDBUTTON             32790
#define ID_VIEW_TOOLBOX                 32791
#define ID_DRAW_EDITWITHBUTTON          32792
#define ID_FILL_ARROW0                  32793
#define ID_LINE_WIDTH                   32794
#define ID_LINE_WIDTH_ARROW0            32795
#define ID_LINE_TYPE                    32796
#define ID_LINE_TYPE_ARROW0             32797
#define ID_LIST_PROP                    32798
#define ID_VIEW_DESIGNMODE              32799
#define ID_ZOOM_VALUE                   32800
#define ID_DRAW_BUTTON                  32801
#define ID_DRAW_MASKEDIT                32802
#define ID_UNDODROPARROW                32803
#define ID_VIEW_RUNMODE                 32804
#define ID_DRAW_CHECKBOX                32805
#define ID_FONT_FACENAME                32806
#define ID_DRAW_COMBOBOX                32807
#define ID_FONT_TYPESIZE                32808
#define ID_FONT_RIGHT_ALIGN             32809
#define ID_FONT_BULLETED                32810
#define ID_FONT_COLOR                   32811
#define ID_FONT_ARROW0                  32812
#define ID_LINE_COLOR                   32813
#define ID_FILL_COLOR                   32814
#define ID_FORMAT_BORDER_FULL           32815
#define ID_FORMAT_BORDER_NONE           32816
#define ID_FORMAT_BORDER_LEFT           32817
#define ID_FORMAT_BORDER_TOP            32818
#define ID_FORMAT_BORDER_RIGHT          32819
#define ID_FORMAT_BORDER_BOTTOM         32820
#define ID_LINE_ARROW0                  32821
#define ID_MOVE_PREVIOUS                32822
#define ID_MOVE_NEXT                    32823
#define ID_W_C_H1                       32824
#define ID_DRAW_LISTBOX                 32825
#define ID_DRAW_PASSWORDEDIT            32826
#define ID_DRAW_MCOMBOBOX               32827
#define ID_VIEW_FONTBAR                 32828
#define ID_VIEW_CONTROLBAR              32829
#define ID_VIEW_FULLSCREEN              32830
#define ID_DROP_MENU                    32831
#define ID_INSERT_OBJECTS               32832
#define ID_DRAW_DATECHOOSE              32833
#define ID_LOOK_STANDARD                32834
#define ID_LOOK_XP                      32835
#define ID_DRAW_MENUEDIT                32836
#define ID_FILE_SAVE_SELECTED           32837
#define ID_SV_SAVE_AS_TEMPLATE_DLG_CREATE 32838
#define ID_SV_SAVE_AS_TEMPLATE_NEW_NAME 32839
#define ID_SV_SAVE_AS_TEMPLATE_REMOVE   32840
#define ID_SV_SAVE_AS_TEMPLATE_DLG_NAME 32841
#define ID_SV_SAVE_AS_TEMPLATE_DLG_TYPE 32842
#define ID_FILE_SAVE_AS_TEMPLATE        32843
#define ID_FO_IMPORT_FILE               32844
#define ID_FO_IMPORT_DBSOURCE           32845
#define ID_SV_RICHEDIT_FONT             32961
#define ID_SV_RICHEDIT_BOLD             32962
#define ID_SV_RICHEDIT_ITALIC           32963
#define ID_SV_RICHEDIT_UNDERLINE        32964
#define ID_SV_RICHEDIT_LEFTALIGN        32965
#define ID_SV_RICHEDIT_CENTERALIGN      32966
#define ID_SV_RICHEDIT_RIGHTALIGN       32967
#define ID_SV_RICHEDIT_INDENT           32968
#define ID_SV_RICHEDIT_OUTDENT          32969
#define ID_SV_RICHEDIT_BULLET           32970
#define ID_SV_RICHEDIT_LINESPACE        33126
#define ID_SV_RICHEDIT_WANTRETURN       33127
#define ID_SV_RICHEDIT_FUNC             33140
#define ID_MB_CREATEPAGE_COPY           40006
#define ID_LAYERS                       40009
#define ID_FONT_TOP_ALIGN               40010
#define ID_FONT_VCENTER_ALIGN           40011
#define ID_FONT_BOTTOM_ALIGN            40013
#define ID_DRAW_AUTOFONT                40015
#define ID_DRAW_NUMBER                  40016
#define ID_FO_DRAW_NEWGRID              40017
#define ID_APP_DRAWING                  40018
#define ID_DRAW_CALC                    40019
#define ID_DRAW_IMAGEBOX                40020
#define ID_TEMPLATE_SAMPLE1             40022
#define ID_TEMPLATE_SAMPLE2             40024
#define ID_SET_DB_NAME                  40025
#define ID_FO_USER_PROP                 40026
#define ID_DRAW_BARCODE                 40027
#define ID_FO_DRAW_BOX                  40028
#define ID_OPEN_TEMPLATE                40029
#define ID_MAIL_TO                      40030
#define ID_NEW_FROM_BLANNK              40031
#define ID_BT_HJ_VIEW                   40032
#define ID_PAGE_OPTION                  40033
#define ID_VIEW_DBNAME                  40034
#define ID_SELECT_ALL_TEXT              40036
#define ID_SLEECT_ALL_FIELDS            40037
#define ID_LOCK_ALL_LABELS              40038
#define ID_LOCK_ALL_FIELDS              40039
#define ID_OFFSET_CANVAS                40040
#define ID_AUTO_SIZE_TEXT               40041
#define ID_DRAW_IMAGE_BOX               40042
#define ID_CHANGE_BINDING               40044
#define ID_DRAW_PIC_BOX                 40045
#define ID_DRAW_SUB_REPORT              40046
#define ID_ONLY_PRINT_ONE               40047
#define ID_DRAW_SYMBOL                  40049
#define ID_DRAW_CHART                   40050

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                1
#define _APS_NEXT_RESOURCE_VALUE        22904
#define _APS_NEXT_COMMAND_VALUE         40051
#define _APS_NEXT_CONTROL_VALUE         1384
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
